### ISSUE TITLE
SimpleTextureExample does not run. But the SimpleSphereExample does. 

### ISSUE THREAD

**Issue by hellerbarde** [arisona/ether#2] opened 2016-05-18 14:39 UTC
It's very weird. I tried to debug it, but I had to give up after 40 minutes.

When I try to start the SimpleTextureExample, instead of opening the window, it just crashes. Here is the runtime error I get: 

```
[LWJGL] GLFW_VERSION_UNAVAILABLE error
    Description : WGL: Failed to create OpenGL context
    Stacktrace  :
        org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1484)
        org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1637)
        ch.fhnw.ether.platform.GLFWWindow.<init>(GLFWWindow.java:130)
        ch.fhnw.ether.platform.GLFWPlatform.createWindow(GLFWPlatform.java:116)
        ch.fhnw.ether.view.IWindow.create(IWindow.java:279)
        ch.fhnw.ether.view.DefaultView.lambda$0(DefaultView.java:69)
        ch.fhnw.ether.platform.GLFWPlatform.run(GLFWPlatform.java:83)
        ch.fhnw.ether.examples.threed.SimpleTextureExample.<init>(SimpleTextureExample.java:129)
        ch.fhnw.ether.examples.threed.SimpleTextureExample.main(SimpleTextureExample.java:56)
java.lang.RuntimeException: failed to create window
    at ch.fhnw.ether.platform.GLFWWindow.<init>(GLFWWindow.java:132)
    at ch.fhnw.ether.platform.GLFWPlatform.createWindow(GLFWPlatform.java:116)
    at ch.fhnw.ether.view.IWindow.create(IWindow.java:279)
    at ch.fhnw.ether.view.DefaultView.lambda$0(DefaultView.java:69)
    at ch.fhnw.ether.platform.GLFWPlatform.run(GLFWPlatform.java:83)
    at ch.fhnw.ether.examples.threed.SimpleTextureExample.<init>(SimpleTextureExample.java:129)
    at ch.fhnw.ether.examples.threed.SimpleTextureExample.main(SimpleTextureExample.java:56)
scheduler: scene thread overload (max=16ms used=320ms)
```

**Comment by arisona** [comment] 2016-05-18 15:23
I cannot reproduce here - it all works fine. This is quite weird, but because the error indicates that the requested opengl version isn't available. We're using the same version for all cases, so it should either work always or never.

I have merged the latest master_dev branch to master - there have been a couple of updates. Maybe it works now?

**Closed as completed** 2016-09-17 12:47 UTC
